# Generated by Django 2.2.3 on 2019-08-11 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='blogging.Post'),
            preserve_default=False,
        ),
    ]
