# Generated by Django 2.2.3 on 2019-08-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20190811_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='post',
            new_name='posts',
        ),
    ]
