# Generated by Django 2.2.3 on 2019-08-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
